import Head from 'next/head'
import ApartmentRoom from '../components/ApartmentRoom/ApartmentRoom'
import Header from '../components/Header/Header'
import Hero from '../components/Hero/Hero'
import HeroCard from '../components/HeroCard/HeroCard'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <HeroCard />
      <ApartmentRoom />

    </div>
  )
}
